/*
 * This file is generated by jOOQ.
 */
package com.fligneul.srm.jooq.tables.records;


import com.fligneul.srm.jooq.tables.Attendance;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttendanceRecord extends UpdatableRecordImpl<AttendanceRecord> implements Record8<Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ATTENDANCE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ATTENDANCE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ATTENDANCE.LICENSEEID</code>.
     */
    public void setLicenseeid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>ATTENDANCE.LICENSEEID</code>.
     */
    public Integer getLicenseeid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>ATTENDANCE.STARTDATE</code>.
     */
    public void setStartdate(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>ATTENDANCE.STARTDATE</code>.
     */
    public LocalDateTime getStartdate() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>ATTENDANCE.STOPDATE</code>.
     */
    public void setStopdate(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>ATTENDANCE.STOPDATE</code>.
     */
    public LocalDateTime getStopdate() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>ATTENDANCE.FIRINGPOINTID</code>.
     */
    public void setFiringpointid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>ATTENDANCE.FIRINGPOINTID</code>.
     */
    public Integer getFiringpointid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>ATTENDANCE.FIRINGPOSTID</code>.
     */
    public void setFiringpostid(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>ATTENDANCE.FIRINGPOSTID</code>.
     */
    public Integer getFiringpostid() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>ATTENDANCE.WEAPONID</code>.
     */
    public void setWeaponid(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>ATTENDANCE.WEAPONID</code>.
     */
    public Integer getWeaponid() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>ATTENDANCE.STATUSID</code>.
     */
    public void setStatusid(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>ATTENDANCE.STATUSID</code>.
     */
    public Integer getStatusid() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Integer, Integer, LocalDateTime, LocalDateTime, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Attendance.ATTENDANCE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Attendance.ATTENDANCE.LICENSEEID;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Attendance.ATTENDANCE.STARTDATE;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return Attendance.ATTENDANCE.STOPDATE;
    }

    @Override
    public Field<Integer> field5() {
        return Attendance.ATTENDANCE.FIRINGPOINTID;
    }

    @Override
    public Field<Integer> field6() {
        return Attendance.ATTENDANCE.FIRINGPOSTID;
    }

    @Override
    public Field<Integer> field7() {
        return Attendance.ATTENDANCE.WEAPONID;
    }

    @Override
    public Field<Integer> field8() {
        return Attendance.ATTENDANCE.STATUSID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getLicenseeid();
    }

    @Override
    public LocalDateTime component3() {
        return getStartdate();
    }

    @Override
    public LocalDateTime component4() {
        return getStopdate();
    }

    @Override
    public Integer component5() {
        return getFiringpointid();
    }

    @Override
    public Integer component6() {
        return getFiringpostid();
    }

    @Override
    public Integer component7() {
        return getWeaponid();
    }

    @Override
    public Integer component8() {
        return getStatusid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getLicenseeid();
    }

    @Override
    public LocalDateTime value3() {
        return getStartdate();
    }

    @Override
    public LocalDateTime value4() {
        return getStopdate();
    }

    @Override
    public Integer value5() {
        return getFiringpointid();
    }

    @Override
    public Integer value6() {
        return getFiringpostid();
    }

    @Override
    public Integer value7() {
        return getWeaponid();
    }

    @Override
    public Integer value8() {
        return getStatusid();
    }

    @Override
    public AttendanceRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public AttendanceRecord value2(Integer value) {
        setLicenseeid(value);
        return this;
    }

    @Override
    public AttendanceRecord value3(LocalDateTime value) {
        setStartdate(value);
        return this;
    }

    @Override
    public AttendanceRecord value4(LocalDateTime value) {
        setStopdate(value);
        return this;
    }

    @Override
    public AttendanceRecord value5(Integer value) {
        setFiringpointid(value);
        return this;
    }

    @Override
    public AttendanceRecord value6(Integer value) {
        setFiringpostid(value);
        return this;
    }

    @Override
    public AttendanceRecord value7(Integer value) {
        setWeaponid(value);
        return this;
    }

    @Override
    public AttendanceRecord value8(Integer value) {
        setStatusid(value);
        return this;
    }

    @Override
    public AttendanceRecord values(Integer value1, Integer value2, LocalDateTime value3, LocalDateTime value4, Integer value5, Integer value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AttendanceRecord
     */
    public AttendanceRecord() {
        super(Attendance.ATTENDANCE);
    }

    /**
     * Create a detached, initialised AttendanceRecord
     */
    public AttendanceRecord(Integer id, Integer licenseeid, LocalDateTime startdate, LocalDateTime stopdate, Integer firingpointid, Integer firingpostid, Integer weaponid, Integer statusid) {
        super(Attendance.ATTENDANCE);

        setId(id);
        setLicenseeid(licenseeid);
        setStartdate(startdate);
        setStopdate(stopdate);
        setFiringpointid(firingpointid);
        setFiringpostid(firingpostid);
        setWeaponid(weaponid);
        setStatusid(statusid);
    }
}
