/*
 * This file is generated by jOOQ.
 */
package com.fligneul.srm.jooq.tables.records;


import com.fligneul.srm.jooq.tables.Firingpost;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FiringpostRecord extends UpdatableRecordImpl<FiringpostRecord> implements Record3<Integer, Integer, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>FIRINGPOST.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>FIRINGPOST.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>FIRINGPOST.FIRINGPOINTID</code>.
     */
    public void setFiringpointid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>FIRINGPOST.FIRINGPOINTID</code>.
     */
    public Integer getFiringpointid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>FIRINGPOST.NAME</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>FIRINGPOST.NAME</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, Integer, String> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, Integer, String> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Firingpost.FIRINGPOST.ID;
    }

    @Override
    public Field<Integer> field2() {
        return Firingpost.FIRINGPOST.FIRINGPOINTID;
    }

    @Override
    public Field<String> field3() {
        return Firingpost.FIRINGPOST.NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getFiringpointid();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getFiringpointid();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public FiringpostRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FiringpostRecord value2(Integer value) {
        setFiringpointid(value);
        return this;
    }

    @Override
    public FiringpostRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public FiringpostRecord values(Integer value1, Integer value2, String value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FiringpostRecord
     */
    public FiringpostRecord() {
        super(Firingpost.FIRINGPOST);
    }

    /**
     * Create a detached, initialised FiringpostRecord
     */
    public FiringpostRecord(Integer id, Integer firingpointid, String name) {
        super(Firingpost.FIRINGPOST);

        setId(id);
        setFiringpointid(firingpointid);
        setName(name);
    }
}
