/*
 * This file is generated by jOOQ.
 */
package com.fligneul.srm.jooq.tables.records;


import com.fligneul.srm.jooq.tables.Licensee;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record21;
import org.jooq.Row21;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.LocalDate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LicenseeRecord extends UpdatableRecordImpl<LicenseeRecord> implements Record21<Integer, String, String, String, String, String, LocalDate, String, String, String, String, String, String, String, String, String, LocalDate, String, String, Boolean, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>LICENSEE.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>LICENSEE.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>LICENSEE.LICENCENUMBER</code>.
     */
    public void setLicencenumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>LICENSEE.LICENCENUMBER</code>.
     */
    public String getLicencenumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>LICENSEE.FIRSTNAME</code>.
     */
    public void setFirstname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>LICENSEE.FIRSTNAME</code>.
     */
    public String getFirstname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>LICENSEE.LASTNAME</code>.
     */
    public void setLastname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>LICENSEE.LASTNAME</code>.
     */
    public String getLastname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>LICENSEE.MAIDENNAME</code>.
     */
    public void setMaidenname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>LICENSEE.MAIDENNAME</code>.
     */
    public String getMaidenname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>LICENSEE.SEX</code>.
     */
    public void setSex(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>LICENSEE.SEX</code>.
     */
    public String getSex() {
        return (String) get(5);
    }

    /**
     * Setter for <code>LICENSEE.DATEOFBIRTH</code>.
     */
    public void setDateofbirth(LocalDate value) {
        set(6, value);
    }

    /**
     * Getter for <code>LICENSEE.DATEOFBIRTH</code>.
     */
    public LocalDate getDateofbirth() {
        return (LocalDate) get(6);
    }

    /**
     * Setter for <code>LICENSEE.PLACEOFBIRTH</code>.
     */
    public void setPlaceofbirth(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>LICENSEE.PLACEOFBIRTH</code>.
     */
    public String getPlaceofbirth() {
        return (String) get(7);
    }

    /**
     * Setter for <code>LICENSEE.DEPARTMENTOFBIRTH</code>.
     */
    public void setDepartmentofbirth(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>LICENSEE.DEPARTMENTOFBIRTH</code>.
     */
    public String getDepartmentofbirth() {
        return (String) get(8);
    }

    /**
     * Setter for <code>LICENSEE.COUNTRYOFBIRTH</code>.
     */
    public void setCountryofbirth(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>LICENSEE.COUNTRYOFBIRTH</code>.
     */
    public String getCountryofbirth() {
        return (String) get(9);
    }

    /**
     * Setter for <code>LICENSEE.ADDRESS</code>.
     */
    public void setAddress(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>LICENSEE.ADDRESS</code>.
     */
    public String getAddress() {
        return (String) get(10);
    }

    /**
     * Setter for <code>LICENSEE.ZIPCODE</code>.
     */
    public void setZipcode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>LICENSEE.ZIPCODE</code>.
     */
    public String getZipcode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>LICENSEE.CITY</code>.
     */
    public void setCity(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>LICENSEE.CITY</code>.
     */
    public String getCity() {
        return (String) get(12);
    }

    /**
     * Setter for <code>LICENSEE.EMAIL</code>.
     */
    public void setEmail(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>LICENSEE.EMAIL</code>.
     */
    public String getEmail() {
        return (String) get(13);
    }

    /**
     * Setter for <code>LICENSEE.PHONENUMBER</code>.
     */
    public void setPhonenumber(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>LICENSEE.PHONENUMBER</code>.
     */
    public String getPhonenumber() {
        return (String) get(14);
    }

    /**
     * Setter for <code>LICENSEE.LICENCESTATE</code>.
     */
    public void setLicencestate(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>LICENSEE.LICENCESTATE</code>.
     */
    public String getLicencestate() {
        return (String) get(15);
    }

    /**
     * Setter for <code>LICENSEE.FIRSTLICENCEDATE</code>.
     */
    public void setFirstlicencedate(LocalDate value) {
        set(16, value);
    }

    /**
     * Getter for <code>LICENSEE.FIRSTLICENCEDATE</code>.
     */
    public LocalDate getFirstlicencedate() {
        return (LocalDate) get(16);
    }

    /**
     * Setter for <code>LICENSEE.SEASON</code>.
     */
    public void setSeason(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>LICENSEE.SEASON</code>.
     */
    public String getSeason() {
        return (String) get(17);
    }

    /**
     * Setter for <code>LICENSEE.AGECATEGORY</code>.
     */
    public void setAgecategory(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>LICENSEE.AGECATEGORY</code>.
     */
    public String getAgecategory() {
        return (String) get(18);
    }

    /**
     * Setter for <code>LICENSEE.HANDISPORT</code>.
     */
    public void setHandisport(Boolean value) {
        set(19, value);
    }

    /**
     * Getter for <code>LICENSEE.HANDISPORT</code>.
     */
    public Boolean getHandisport() {
        return (Boolean) get(19);
    }

    /**
     * Setter for <code>LICENSEE.BLACKLISTED</code>.
     */
    public void setBlacklisted(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>LICENSEE.BLACKLISTED</code>.
     */
    public Boolean getBlacklisted() {
        return (Boolean) get(20);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record21 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row21<Integer, String, String, String, String, String, LocalDate, String, String, String, String, String, String, String, String, String, LocalDate, String, String, Boolean, Boolean> fieldsRow() {
        return (Row21) super.fieldsRow();
    }

    @Override
    public Row21<Integer, String, String, String, String, String, LocalDate, String, String, String, String, String, String, String, String, String, LocalDate, String, String, Boolean, Boolean> valuesRow() {
        return (Row21) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Licensee.LICENSEE.ID;
    }

    @Override
    public Field<String> field2() {
        return Licensee.LICENSEE.LICENCENUMBER;
    }

    @Override
    public Field<String> field3() {
        return Licensee.LICENSEE.FIRSTNAME;
    }

    @Override
    public Field<String> field4() {
        return Licensee.LICENSEE.LASTNAME;
    }

    @Override
    public Field<String> field5() {
        return Licensee.LICENSEE.MAIDENNAME;
    }

    @Override
    public Field<String> field6() {
        return Licensee.LICENSEE.SEX;
    }

    @Override
    public Field<LocalDate> field7() {
        return Licensee.LICENSEE.DATEOFBIRTH;
    }

    @Override
    public Field<String> field8() {
        return Licensee.LICENSEE.PLACEOFBIRTH;
    }

    @Override
    public Field<String> field9() {
        return Licensee.LICENSEE.DEPARTMENTOFBIRTH;
    }

    @Override
    public Field<String> field10() {
        return Licensee.LICENSEE.COUNTRYOFBIRTH;
    }

    @Override
    public Field<String> field11() {
        return Licensee.LICENSEE.ADDRESS;
    }

    @Override
    public Field<String> field12() {
        return Licensee.LICENSEE.ZIPCODE;
    }

    @Override
    public Field<String> field13() {
        return Licensee.LICENSEE.CITY;
    }

    @Override
    public Field<String> field14() {
        return Licensee.LICENSEE.EMAIL;
    }

    @Override
    public Field<String> field15() {
        return Licensee.LICENSEE.PHONENUMBER;
    }

    @Override
    public Field<String> field16() {
        return Licensee.LICENSEE.LICENCESTATE;
    }

    @Override
    public Field<LocalDate> field17() {
        return Licensee.LICENSEE.FIRSTLICENCEDATE;
    }

    @Override
    public Field<String> field18() {
        return Licensee.LICENSEE.SEASON;
    }

    @Override
    public Field<String> field19() {
        return Licensee.LICENSEE.AGECATEGORY;
    }

    @Override
    public Field<Boolean> field20() {
        return Licensee.LICENSEE.HANDISPORT;
    }

    @Override
    public Field<Boolean> field21() {
        return Licensee.LICENSEE.BLACKLISTED;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLicencenumber();
    }

    @Override
    public String component3() {
        return getFirstname();
    }

    @Override
    public String component4() {
        return getLastname();
    }

    @Override
    public String component5() {
        return getMaidenname();
    }

    @Override
    public String component6() {
        return getSex();
    }

    @Override
    public LocalDate component7() {
        return getDateofbirth();
    }

    @Override
    public String component8() {
        return getPlaceofbirth();
    }

    @Override
    public String component9() {
        return getDepartmentofbirth();
    }

    @Override
    public String component10() {
        return getCountryofbirth();
    }

    @Override
    public String component11() {
        return getAddress();
    }

    @Override
    public String component12() {
        return getZipcode();
    }

    @Override
    public String component13() {
        return getCity();
    }

    @Override
    public String component14() {
        return getEmail();
    }

    @Override
    public String component15() {
        return getPhonenumber();
    }

    @Override
    public String component16() {
        return getLicencestate();
    }

    @Override
    public LocalDate component17() {
        return getFirstlicencedate();
    }

    @Override
    public String component18() {
        return getSeason();
    }

    @Override
    public String component19() {
        return getAgecategory();
    }

    @Override
    public Boolean component20() {
        return getHandisport();
    }

    @Override
    public Boolean component21() {
        return getBlacklisted();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLicencenumber();
    }

    @Override
    public String value3() {
        return getFirstname();
    }

    @Override
    public String value4() {
        return getLastname();
    }

    @Override
    public String value5() {
        return getMaidenname();
    }

    @Override
    public String value6() {
        return getSex();
    }

    @Override
    public LocalDate value7() {
        return getDateofbirth();
    }

    @Override
    public String value8() {
        return getPlaceofbirth();
    }

    @Override
    public String value9() {
        return getDepartmentofbirth();
    }

    @Override
    public String value10() {
        return getCountryofbirth();
    }

    @Override
    public String value11() {
        return getAddress();
    }

    @Override
    public String value12() {
        return getZipcode();
    }

    @Override
    public String value13() {
        return getCity();
    }

    @Override
    public String value14() {
        return getEmail();
    }

    @Override
    public String value15() {
        return getPhonenumber();
    }

    @Override
    public String value16() {
        return getLicencestate();
    }

    @Override
    public LocalDate value17() {
        return getFirstlicencedate();
    }

    @Override
    public String value18() {
        return getSeason();
    }

    @Override
    public String value19() {
        return getAgecategory();
    }

    @Override
    public Boolean value20() {
        return getHandisport();
    }

    @Override
    public Boolean value21() {
        return getBlacklisted();
    }

    @Override
    public LicenseeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public LicenseeRecord value2(String value) {
        setLicencenumber(value);
        return this;
    }

    @Override
    public LicenseeRecord value3(String value) {
        setFirstname(value);
        return this;
    }

    @Override
    public LicenseeRecord value4(String value) {
        setLastname(value);
        return this;
    }

    @Override
    public LicenseeRecord value5(String value) {
        setMaidenname(value);
        return this;
    }

    @Override
    public LicenseeRecord value6(String value) {
        setSex(value);
        return this;
    }

    @Override
    public LicenseeRecord value7(LocalDate value) {
        setDateofbirth(value);
        return this;
    }

    @Override
    public LicenseeRecord value8(String value) {
        setPlaceofbirth(value);
        return this;
    }

    @Override
    public LicenseeRecord value9(String value) {
        setDepartmentofbirth(value);
        return this;
    }

    @Override
    public LicenseeRecord value10(String value) {
        setCountryofbirth(value);
        return this;
    }

    @Override
    public LicenseeRecord value11(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public LicenseeRecord value12(String value) {
        setZipcode(value);
        return this;
    }

    @Override
    public LicenseeRecord value13(String value) {
        setCity(value);
        return this;
    }

    @Override
    public LicenseeRecord value14(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public LicenseeRecord value15(String value) {
        setPhonenumber(value);
        return this;
    }

    @Override
    public LicenseeRecord value16(String value) {
        setLicencestate(value);
        return this;
    }

    @Override
    public LicenseeRecord value17(LocalDate value) {
        setFirstlicencedate(value);
        return this;
    }

    @Override
    public LicenseeRecord value18(String value) {
        setSeason(value);
        return this;
    }

    @Override
    public LicenseeRecord value19(String value) {
        setAgecategory(value);
        return this;
    }

    @Override
    public LicenseeRecord value20(Boolean value) {
        setHandisport(value);
        return this;
    }

    @Override
    public LicenseeRecord value21(Boolean value) {
        setBlacklisted(value);
        return this;
    }

    @Override
    public LicenseeRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, LocalDate value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, LocalDate value17, String value18, String value19, Boolean value20, Boolean value21) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached LicenseeRecord
     */
    public LicenseeRecord() {
        super(Licensee.LICENSEE);
    }

    /**
     * Create a detached, initialised LicenseeRecord
     */
    public LicenseeRecord(Integer id, String licencenumber, String firstname, String lastname, String maidenname, String sex, LocalDate dateofbirth, String placeofbirth, String departmentofbirth, String countryofbirth, String address, String zipcode, String city, String email, String phonenumber, String licencestate, LocalDate firstlicencedate, String season, String agecategory, Boolean handisport, Boolean blacklisted) {
        super(Licensee.LICENSEE);

        setId(id);
        setLicencenumber(licencenumber);
        setFirstname(firstname);
        setLastname(lastname);
        setMaidenname(maidenname);
        setSex(sex);
        setDateofbirth(dateofbirth);
        setPlaceofbirth(placeofbirth);
        setDepartmentofbirth(departmentofbirth);
        setCountryofbirth(countryofbirth);
        setAddress(address);
        setZipcode(zipcode);
        setCity(city);
        setEmail(email);
        setPhonenumber(phonenumber);
        setLicencestate(licencestate);
        setFirstlicencedate(firstlicencedate);
        setSeason(season);
        setAgecategory(agecategory);
        setHandisport(handisport);
        setBlacklisted(blacklisted);
    }
}
