/*
 * This file is generated by jOOQ.
 */
package com.fligneul.srm.jooq.tables.records;


import com.fligneul.srm.jooq.tables.Shootingsession;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ShootingsessionRecord extends UpdatableRecordImpl<ShootingsessionRecord> implements Record5<Integer, LocalDate, String, Integer, Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>SHOOTINGSESSION.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>SHOOTINGSESSION.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>SHOOTINGSESSION.SESSIONDATE</code>.
     */
    public void setSessiondate(LocalDate value) {
        set(1, value);
    }

    /**
     * Getter for <code>SHOOTINGSESSION.SESSIONDATE</code>.
     */
    public LocalDate getSessiondate() {
        return (LocalDate) get(1);
    }

    /**
     * Setter for <code>SHOOTINGSESSION.INSTRUCTORNAME</code>.
     */
    public void setInstructorname(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>SHOOTINGSESSION.INSTRUCTORNAME</code>.
     */
    public String getInstructorname() {
        return (String) get(2);
    }

    /**
     * Setter for <code>SHOOTINGSESSION.SHOOTINGLOGBOOKID</code>.
     */
    public void setShootinglogbookid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>SHOOTINGSESSION.SHOOTINGLOGBOOKID</code>.
     */
    public Integer getShootinglogbookid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>SHOOTINGSESSION.WEAPONID</code>.
     */
    public void setWeaponid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>SHOOTINGSESSION.WEAPONID</code>.
     */
    public Integer getWeaponid() {
        return (Integer) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, LocalDate, String, Integer, Integer> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, LocalDate, String, Integer, Integer> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Shootingsession.SHOOTINGSESSION.ID;
    }

    @Override
    public Field<LocalDate> field2() {
        return Shootingsession.SHOOTINGSESSION.SESSIONDATE;
    }

    @Override
    public Field<String> field3() {
        return Shootingsession.SHOOTINGSESSION.INSTRUCTORNAME;
    }

    @Override
    public Field<Integer> field4() {
        return Shootingsession.SHOOTINGSESSION.SHOOTINGLOGBOOKID;
    }

    @Override
    public Field<Integer> field5() {
        return Shootingsession.SHOOTINGSESSION.WEAPONID;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public LocalDate component2() {
        return getSessiondate();
    }

    @Override
    public String component3() {
        return getInstructorname();
    }

    @Override
    public Integer component4() {
        return getShootinglogbookid();
    }

    @Override
    public Integer component5() {
        return getWeaponid();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public LocalDate value2() {
        return getSessiondate();
    }

    @Override
    public String value3() {
        return getInstructorname();
    }

    @Override
    public Integer value4() {
        return getShootinglogbookid();
    }

    @Override
    public Integer value5() {
        return getWeaponid();
    }

    @Override
    public ShootingsessionRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public ShootingsessionRecord value2(LocalDate value) {
        setSessiondate(value);
        return this;
    }

    @Override
    public ShootingsessionRecord value3(String value) {
        setInstructorname(value);
        return this;
    }

    @Override
    public ShootingsessionRecord value4(Integer value) {
        setShootinglogbookid(value);
        return this;
    }

    @Override
    public ShootingsessionRecord value5(Integer value) {
        setWeaponid(value);
        return this;
    }

    @Override
    public ShootingsessionRecord values(Integer value1, LocalDate value2, String value3, Integer value4, Integer value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ShootingsessionRecord
     */
    public ShootingsessionRecord() {
        super(Shootingsession.SHOOTINGSESSION);
    }

    /**
     * Create a detached, initialised ShootingsessionRecord
     */
    public ShootingsessionRecord(Integer id, LocalDate sessiondate, String instructorname, Integer shootinglogbookid, Integer weaponid) {
        super(Shootingsession.SHOOTINGSESSION);

        setId(id);
        setSessiondate(sessiondate);
        setInstructorname(instructorname);
        setShootinglogbookid(shootinglogbookid);
        setWeaponid(weaponid);
    }
}
