/*
 * This file is generated by jOOQ.
 */
package com.fligneul.srm.jooq.tables.records;


import com.fligneul.srm.jooq.tables.Weapon;

import java.time.LocalDate;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WeaponRecord extends UpdatableRecordImpl<WeaponRecord> implements Record5<Integer, String, Integer, String, LocalDate> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>WEAPON.ID</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>WEAPON.ID</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>WEAPON.NAME</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>WEAPON.NAME</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>WEAPON.IDENTIFICATIONNUMBER</code>.
     */
    public void setIdentificationnumber(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>WEAPON.IDENTIFICATIONNUMBER</code>.
     */
    public Integer getIdentificationnumber() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>WEAPON.CALIBER</code>.
     */
    public void setCaliber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>WEAPON.CALIBER</code>.
     */
    public String getCaliber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>WEAPON.BUYDATE</code>.
     */
    public void setBuydate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>WEAPON.BUYDATE</code>.
     */
    public LocalDate getBuydate() {
        return (LocalDate) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, String, Integer, String, LocalDate> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, String, Integer, String, LocalDate> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Weapon.WEAPON.ID;
    }

    @Override
    public Field<String> field2() {
        return Weapon.WEAPON.NAME;
    }

    @Override
    public Field<Integer> field3() {
        return Weapon.WEAPON.IDENTIFICATIONNUMBER;
    }

    @Override
    public Field<String> field4() {
        return Weapon.WEAPON.CALIBER;
    }

    @Override
    public Field<LocalDate> field5() {
        return Weapon.WEAPON.BUYDATE;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public Integer component3() {
        return getIdentificationnumber();
    }

    @Override
    public String component4() {
        return getCaliber();
    }

    @Override
    public LocalDate component5() {
        return getBuydate();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public Integer value3() {
        return getIdentificationnumber();
    }

    @Override
    public String value4() {
        return getCaliber();
    }

    @Override
    public LocalDate value5() {
        return getBuydate();
    }

    @Override
    public WeaponRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public WeaponRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public WeaponRecord value3(Integer value) {
        setIdentificationnumber(value);
        return this;
    }

    @Override
    public WeaponRecord value4(String value) {
        setCaliber(value);
        return this;
    }

    @Override
    public WeaponRecord value5(LocalDate value) {
        setBuydate(value);
        return this;
    }

    @Override
    public WeaponRecord values(Integer value1, String value2, Integer value3, String value4, LocalDate value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WeaponRecord
     */
    public WeaponRecord() {
        super(Weapon.WEAPON);
    }

    /**
     * Create a detached, initialised WeaponRecord
     */
    public WeaponRecord(Integer id, String name, Integer identificationnumber, String caliber, LocalDate buydate) {
        super(Weapon.WEAPON);

        setId(id);
        setName(name);
        setIdentificationnumber(identificationnumber);
        setCaliber(caliber);
        setBuydate(buydate);
    }
}
