/*
 * This file is generated by jOOQ.
 */
package com.fligneul.srm.jooq;


import com.fligneul.srm.jooq.tables.Attendance;
import com.fligneul.srm.jooq.tables.Firingpoint;
import com.fligneul.srm.jooq.tables.Firingpost;
import com.fligneul.srm.jooq.tables.Licensee;
import com.fligneul.srm.jooq.tables.User;
import com.fligneul.srm.jooq.tables.Weapon;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>DEFAULT_SCHEMA</code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>ATTENDANCE</code>.
     */
    public final Attendance ATTENDANCE = Attendance.ATTENDANCE;

    /**
     * The table <code>FIRINGPOINT</code>.
     */
    public final Firingpoint FIRINGPOINT = Firingpoint.FIRINGPOINT;

    /**
     * The table <code>FIRINGPOST</code>.
     */
    public final Firingpost FIRINGPOST = Firingpost.FIRINGPOST;

    /**
     * The table <code>LICENSEE</code>.
     */
    public final Licensee LICENSEE = Licensee.LICENSEE;

    /**
     * The table <code>USER</code>.
     */
    public final User USER = User.USER;

    /**
     * The table <code>WEAPON</code>.
     */
    public final Weapon WEAPON = Weapon.WEAPON;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Attendance.ATTENDANCE,
            Firingpoint.FIRINGPOINT,
            Firingpost.FIRINGPOST,
            Licensee.LICENSEE,
            User.USER,
            Weapon.WEAPON
        );
    }
}
