/*
 * This file is generated by jOOQ.
 */
package com.fligneul.srm.jooq;


import com.fligneul.srm.jooq.tables.Attendance;
import com.fligneul.srm.jooq.tables.Firingpoint;
import com.fligneul.srm.jooq.tables.Firingpost;
import com.fligneul.srm.jooq.tables.Licensee;
import com.fligneul.srm.jooq.tables.Shootinglogbook;
import com.fligneul.srm.jooq.tables.Shootingsession;
import com.fligneul.srm.jooq.tables.User;
import com.fligneul.srm.jooq.tables.Weapon;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>ATTENDANCE</code>.
     */
    public static final Attendance ATTENDANCE = Attendance.ATTENDANCE;

    /**
     * The table <code>FIRINGPOINT</code>.
     */
    public static final Firingpoint FIRINGPOINT = Firingpoint.FIRINGPOINT;

    /**
     * The table <code>FIRINGPOST</code>.
     */
    public static final Firingpost FIRINGPOST = Firingpost.FIRINGPOST;

    /**
     * The table <code>LICENSEE</code>.
     */
    public static final Licensee LICENSEE = Licensee.LICENSEE;

    /**
     * The table <code>SHOOTINGLOGBOOK</code>.
     */
    public static final Shootinglogbook SHOOTINGLOGBOOK = Shootinglogbook.SHOOTINGLOGBOOK;

    /**
     * The table <code>SHOOTINGSESSION</code>.
     */
    public static final Shootingsession SHOOTINGSESSION = Shootingsession.SHOOTINGSESSION;

    /**
     * The table <code>USER</code>.
     */
    public static final User USER = User.USER;

    /**
     * The table <code>WEAPON</code>.
     */
    public static final Weapon WEAPON = Weapon.WEAPON;
}
