/*
 * This file is generated by jOOQ.
 */
package com.fligneul.srm.jooq.tables;


import com.fligneul.srm.jooq.DefaultSchema;
import com.fligneul.srm.jooq.Keys;
import com.fligneul.srm.jooq.tables.records.FiringpointRecord;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row2;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Firingpoint extends TableImpl<FiringpointRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>FIRINGPOINT</code>
     */
    public static final Firingpoint FIRINGPOINT = new Firingpoint();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FiringpointRecord> getRecordType() {
        return FiringpointRecord.class;
    }

    /**
     * The column <code>FIRINGPOINT.ID</code>.
     */
    public final TableField<FiringpointRecord, Integer> ID = createField(DSL.name("ID"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>FIRINGPOINT.NAME</code>.
     */
    public final TableField<FiringpointRecord, String> NAME = createField(DSL.name("NAME"), SQLDataType.VARCHAR(50), this, "");

    private Firingpoint(Name alias, Table<FiringpointRecord> aliased) {
        this(alias, aliased, null);
    }

    private Firingpoint(Name alias, Table<FiringpointRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>FIRINGPOINT</code> table reference
     */
    public Firingpoint(String alias) {
        this(DSL.name(alias), FIRINGPOINT);
    }

    /**
     * Create an aliased <code>FIRINGPOINT</code> table reference
     */
    public Firingpoint(Name alias) {
        this(alias, FIRINGPOINT);
    }

    /**
     * Create a <code>FIRINGPOINT</code> table reference
     */
    public Firingpoint() {
        this(DSL.name("FIRINGPOINT"), null);
    }

    public <O extends Record> Firingpoint(Table<O> child, ForeignKey<O, FiringpointRecord> key) {
        super(child, key, FIRINGPOINT);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : DefaultSchema.DEFAULT_SCHEMA;
    }

    @Override
    public Identity<FiringpointRecord, Integer> getIdentity() {
        return (Identity<FiringpointRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<FiringpointRecord> getPrimaryKey() {
        return Keys.PK_FIRINGPOINT;
    }

    @Override
    public Firingpoint as(String alias) {
        return new Firingpoint(DSL.name(alias), this);
    }

    @Override
    public Firingpoint as(Name alias) {
        return new Firingpoint(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Firingpoint rename(String name) {
        return new Firingpoint(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Firingpoint rename(Name name) {
        return new Firingpoint(name, null);
    }

    // -------------------------------------------------------------------------
    // Row2 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }
}
